name: Deploy Web (Pages)

on:
  push:
    branches: [main]
    paths:
      - "apps/kanban-web/**"
      - "package.json"
      - "package-lock.json"
      - "turbo.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            **/package-lock.json

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build site
        working-directory: apps/kanban-web
        run: npm run build

      - name: Ensure Pages project exists (idempotent)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: pages project create kanban-web --production-branch=main
        continue-on-error: true

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: pages deploy ./apps/kanban-web/dist --project-name=kanban-web
