name: Deploy Web (Pages)

on:
  push:
    branches: [master]
    paths:
      - "apps/kanban-web/**"
      - "package.json"
      - "package-lock.json"
      - "turbo.json"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            **/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build site
        working-directory: apps/kanban-web
        run: npm run build

      - name: Ensure Pages project exists (idempotent)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages project create kanban-web --production-branch=master
        continue-on-error: true

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./apps/kanban-web/dist --project-name=kanban-web --commit-dirty=true
